
DROP TABLE IF EXISTS "PostTags";
DROP TABLE IF EXISTS "Comment";
DROP TABLE IF EXISTS "Post";
DROP TABLE IF EXISTS "Account";
DROP TABLE IF EXISTS "Session";
DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "VerificationToken";
